[package]
name = "rust-performance-timing"
version = "0.1.0"
authors = ["Ilya Albrecht <ilya@alfs.me>"]
edition = "2018"

[dependencies]
criterion = "0.3"

[[bench]]
name = "criterion_cycle_bench"
harness = false
